### ISSUE TITLE
vm.Script.runInThisContext.call(... "Cannot read property 'call' of undefined"

### ISSUE THREAD

**Issue by ilyador** [swannodette/mies-node-template#5]
I followed the instructions and I get this:

```
$ node run.js

/hello-world/out/goog/bootstrap/nodejs.js:85
  vm.Script.runInThisContext.call(global, fs.readFileSync(file), file);
                            ^
TypeError: Cannot read property 'call' of undefined
    at nodeGlobalRequire (/hello-world/out/goog/bootstrap/nodejs.js:85:29)
    at Object.<anonymous> (/hello-world/out/goog/bootstrap/nodejs.js:94:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/hello-world/run.js:5:1)
    at Module._compile (module.js:460:26)

**Comment by swannodette** [comment]
@ilyador you're running Node.js 0.12 with an older version of ClojureScript, just bump the version of ClojureScript to 0.0-3196 in your project.clj. I'll get around to fixing this properly likely around the time we ship a stable ClojureScript release to coincide with Cojure 1.7.0.

**Comment by robjens** [comment]
@swannodette I tried doing just that but it doesn't work over here though, the `3196` inclusion that is, same error as OP. `v0.12.2` of node here though so I'll have a go at downgrading my build a bit to see how it works under those conditions .. I guess `12.0` still might work as suggested, if not I'll drop to 11, maybe even 10 to see if it has any effect

**Comment by danjacka** [comment]
Same problem here. I tried bumping to the latest version (`0.0-3211`) but no dice.

**Comment by wiseman** [comment]
I ran into this also.  Is it time to update the clojurescript version in the template yet?

**Comment by wiseman** [comment]
Sorry, I completely missed that this project is deprecated (despite that being the second line in the README)!

Is there a new recommended template for creating a node clojurescript project?

**Comment by robjens** [comment]
@wiseman AFAIK not. Did a quick rundown using github.com/search but nothing current. Although I must say, with current day quality of the cljs wiki, it hardly is needed. Checkout https://github.com/clojure/clojurescript/wiki/Quick-Start#running-clojurescript-on-nodejs and from that, I'm sure you'll be able to write up your own boilerplat/starter if you want. It certainly is much more straightforward than it used to be.
